version: "3"
services:
  redis:
    image: redis:7.0.5
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    environment:
      - TZ=GMT+8
    networks:
      - devops

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=GMT+8
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "/software/data/mysql:/var/lib/mysql"
      - "/software/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    ports:
      - "3306:3306"
    networks:
      - devops

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - TZ=GMT+8
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831"
      - "16686:16686"
      - "9411:9411"
    networks:
      - devops

networks:
  devops:
