## 应用名称, 运行模式, http端口, grpc端口, 应用外网地址, 是否开启入参出参打印, 应用版本号
[app]
url = "http://127.0.0.1:80"
mod = "dev1"
name = "laya-template"
run_mode = "debug"
http_listen = "0.0.0.0:80"
grpc_listen = "0.0.0.0:81"
params = true
version = "1.0.0"

## 应用日志的配置(路径和保留天数和打印在控制台还是文件中)(默认开启7天, 最大日志保留30个, 单个日志大小是128M, 7天内日志最大到3.75G)
[app.logger]
type = "file"
path = "/home/logs/app"
max_age = 7
max_count = 30

## 应用链路追踪上报(支持zipkin和jaeger), 采样率是0-1, 0是关闭链路追踪
## zipkin_addr参考设置http://127.0.0.1:9411/api/v2/spans
## jaeger_addr参考设置127.0.0.1:6831
[app.trace]
type = "jaeger"
addr = "127.0.0.1:6831"
mod = 1

## 告警处理
[app.alarm]
type = "dingding"
key = "SEC1a82878eaff2feda60e828e7950269922f0507b32a87713baf3dc40ecd4ef699"
addr = "https://oapi.dingtalk.com/robot/send?access_token=f5c1a139feca09534c58e5e136137f1fe5af4bde93a0d3883c5756c7f3741367"


## service name是唯一值, 对应服务名, 默认连接超时时间是(1500ms), 必须带上协议头(http,https,grpc)
[[services]]
name = "http_test"
addr = "http://127.0.0.1:10081"
[[services]]
name = "grpc_test"
addr = "grpc://127.0.0.1:10082"

## mysql配置, name数据库连接唯一标识, 应用有多个库的时候使用
## 支持设置max_idle_conn空闲连接数,max_open_conn最大连接数,max_life_time连接可重用的最大时间秒,max_idle_time在关闭连接之前连接可能处于空闲状态的最大时间秒
## 支持设置日志等级, 默认info, 枚举(info,warn,error)
[[mysql]]
name = "default"
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_template?charset=utf8&parseTime=True&loc=Local"
level = "error"
max_idle_conn = 1
[[mysql]]
name = "laya_template"
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_template?charset=utf8&parseTime=True&loc=Local"

## redis配置
[[redis]]
name = "default"
addr = "127.0.0.1:6379"
db = 0
pwd = "123456"

## mongo pool_max_open pool_max_idle conn_max_idle_time
[[mongo]]
name = "default"
uri = "mongodb://root:123456@127.0.0.1:27017"

## es
[[es]]
name = "default"
host = "http://127.0.0.1:4711"
user = ""
pwd = ""

## extra其他配置
[extra]

## 错误码配置
[err_code]
"400" = "system error"
"4002" = "surprise"