[app]
name = "laya-go"
mode = "dev1"
run_mode = "debug"
http_listen = "0.0.0.0:80"
url = "http://127.0.0.1:80"
pprof = true
params = true
logger = "/home/logs/app"
version = "1.0.0"

[mysql]
dsn = "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local"

[err_code]
"4001" = "hello world"
"4002" = "surprice"