## app基础配置
## mod 标识该应用的运行环境 默认值是"dev", "test", "pre"，"prod" 支持前缀例如: dev-1.0.0, 实际运行是dev
## dev和test会自动开启pprof,gin是debug模式, pre，prod是release模式并且关闭了pprof
## name 应用名 默认值是"normal"
## listen 服务的监听地址 默认值是"0.0.0.0:81"
## version 当前服务的版本号 默认值是"1.0.0"
[app]
mod = "dev"
name = "laya-template"
listen = "0.0.0.0:10080"
version = "1.0.0"

## 应用日志的配置(单个日志大小是128M, 7天内日志最大到3.75G)
## type 日志类型 "file" "console" 默认值是"file"
## path 日志路劲 "/home/logs/app" 默认值是"/home/logs/" 最终路径是/home/logs/{{.app_name}}/2022-03-21.log
## max_age 配置保留天数 7 默认值是7 (日志保留最近7天)
## max_count 配置保留文件个数 30 默认值是30 (保留最近的30个文件)
## max_size 单个文件最大多少byte
## child_path 子目录, 默认值是"%Y-%m-%d.log"
## 支持debug info warn error 4个日志等级
[app.logger]

## 应用需要的出入参打印, 默认是全打印, 建议配置核心业务
## sdk表示请求其他服务是否需要打印
## prefix前缀，suffix后缀, 支持*，不支持正则和模糊
[app.logger.params]
sdk = true
log_uri = ["*"]
log_uri_prefix = []
log_uri_suffix = []

## 应用链路追踪上报(支持zipkin和jaeger)
## type 是链路追钟的类型 "zipkin" "jaeger" 默认值是空 (默认值是空的时候表示没有链路处理)
## addr 是链路追踪的上报地址 默认值是空 (zipkin_addr参考设置http://127.0.0.1:9411/api/v2/spans, jaeger_addr参考设置127.0.0.1:6831)http://localhost:14268/api/traces
## mod 采样率0-1 默认值是0
[app.trace]
type = "jaeger"
addr = "http://127.0.0.1:14268/api/traces"
mod = 1

## 告警处理(dingding和http和飞书)
## type 表示告警处理的类型 默认值是空 (默认值是空的时候表示没有告警处理)
## key 表示告警的密钥 默认值是空
## addr 告警提交的地址 默认值是空
[app.alarm]
type = ""
key = ""
addr = ""

## mysql配置, name数据库连接唯一标识, 应用有多个库的时候使用
## name 数据库标识唯一名 default 默认连接,在使用时没有传入表示使用默认连接
## dsn 数据库连接dsn
## max_idle_conn 空闲连接数 默认值是2
## max_open_conn 最大连接数 默认值是cpu*2+5
## max_life_time 连接可重用的最大时间秒 默认值是7200s
## max_idle_time 在关闭连接之前连接可能处于空闲状态的最大时间秒 默认值是60s
[[mysql]]
name = "default"
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_template?charset=utf8&parseTime=True&loc=Local"
[[mysql]]
name = "laya_template"
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_template?charset=utf8&parseTime=True&loc=Local"

## redis配置
## name redis连接唯一标识
## addr redis连接地址
## db redis连接数据库
## pwd redis密码
[[redis]]
name = "default"
addr = "127.0.0.1:6379"
db = 0
pwd = ""

## mongo 配置
## name mongo连接唯一标识
## dsn mongo连接地址
## max_open_conn
## max_idle_conn
## max_idle_time
[[mongo]]
name = "default"
dsn = "mongodb://root:123456@127.0.0.1:27017/?authSource=admin"

## es 配置
## name es连接唯一标识
## host es连接地址
## user 用户名
## pwd 密码
[[es]]
name = "default"
dsn = "http://127.0.0.1:9200"

## 内部服务连接池配置
## name 服务名(唯一)
## addr 服务地址 必须带上协议头(http,https,grpc)
## retry 重试次数 默认值是0 (不重试)
## conn_time_out 连接超时时间 默认值是1500ms
## write_time_out 写入超时时间 默认值是1500ms
## read_time_out 读取超时时间 默认值是1500ms
[[services]]
name = "http_test"
addr = "http://127.0.0.1:10081"
[[services]]
name = "grpc_test"
addr = "grpc://127.0.0.1:10082"

## extra其他配置
[extra]
auto_metrics = "prometheus"
